Repository TeamDAYORI/dayori-spring, pull requests merged in 2023-08, with the labels that each got.

#36 feat: [Diary] 유저 및 권한 관련 수정 및 response 메시지 수정
  spring-boot/src/main/java/com/tody/dayori/diary/constant/DiaryConstant.java
  spring-boot/src/main/java/com/tody/dayori/diary/controller/DiaryController.java
  spring-boot/src/main/java/com/tody/dayori/diary/service/DiaryServiceImpl.java
Labels: feature

#35 refactor: [Security] 시큐리티 로직 개선
  spring-boot/src/main/java/com/tody/dayori/auth/controller/AuthController.java
  spring-boot/src/main/java/com/tody/dayori/auth/dto/AuthResponse.java
  spring-boot/src/main/java/com/tody/dayori/auth/dto/LoginRequest.java
  spring-boot/src/main/java/com/tody/dayori/auth/dto/SignUpRequest.java
  spring-boot/src/main/java/com/tody/dayori/auth/entity/Role.java
  spring-boot/src/main/java/com/tody/dayori/auth/entity/User.java
  spring-boot/src/main/java/com/tody/dayori/auth/service/JwtProvider.java
  spring-boot/src/main/java/com/tody/dayori/auth/service/UserServiceImpl.java
  spring-boot/src/main/java/com/tody/dayori/common/util/TokenUtil.java
  spring-boot/src/main/java/com/tody/dayori/config/ApplicationConfig.java
  spring-boot/src/main/java/com/tody/dayori/config/JwtAuthFilter.java
  spring-boot/src/main/java/com/tody/dayori/config/JwtProvider.java
  spring-boot/src/main/java/com/tody/dayori/config/SecurityConfig.java
  spring-boot/src/main/java/com/tody/dayori/page/service/PageServiceImpl.java
  spring-boot/src/main/resources/application.yml
Labels: refactor

#38 feat: [Diary] 다이어리 탈퇴, 멤버 초대 api
  spring-boot/src/main/java/com/tody/dayori/auth/dto/SignUpRequest.java
  spring-boot/src/main/java/com/tody/dayori/auth/entity/User.java
  spring-boot/src/main/java/com/tody/dayori/auth/repository/UserRepository.java
  spring-boot/src/main/java/com/tody/dayori/auth/service/UserServiceImpl.java
  spring-boot/src/main/java/com/tody/dayori/diary/constant/DiaryConstant.java
  spring-boot/src/main/java/com/tody/dayori/diary/controller/DiaryController.java
  spring-boot/src/main/java/com/tody/dayori/diary/domain/Diary.java
  spring-boot/src/main/java/com/tody/dayori/diary/domain/UserDiary.java
  spring-boot/src/main/java/com/tody/dayori/diary/dto/CreateDiaryRequest.java
  spring-boot/src/main/java/com/tody/dayori/diary/dto/SearchUserResponse.java
  spring-boot/src/main/java/com/tody/dayori/diary/repository/UserDiaryRepository.java
  spring-boot/src/main/java/com/tody/dayori/diary/service/DiaryServiceImpl.java
Labels: feature

#42 feat: [Security] 요청에서 유저 객체 가져오기
  spring-boot/src/main/java/com/tody/dayori/auth/controller/AuthController.java
  spring-boot/src/main/java/com/tody/dayori/auth/service/UserServiceImpl.java
  spring-boot/src/main/java/com/tody/dayori/common/util/TokenUtil.java
  spring-boot/src/main/java/com/tody/dayori/config/SecurityConfig.java
  spring-boot/src/main/java/com/tody/dayori/config/WebConfig.java
  spring-boot/src/main/resources/application.yml
Labels: work, bug

#44 feat: [Diary] 멤버 초대 예외처리 추가, 다이어리 목록 정렬
  spring-boot/src/main/java/com/tody/dayori/auth/repository/UserRepository.java
  spring-boot/src/main/java/com/tody/dayori/common/exception/DuplicateException.java
  spring-boot/src/main/java/com/tody/dayori/common/exception/NotMatchException.java
  spring-boot/src/main/java/com/tody/dayori/config/JwtProvider.java
  spring-boot/src/main/java/com/tody/dayori/diary/controller/DiaryController.java
  spring-boot/src/main/java/com/tody/dayori/diary/domain/UserDiary.java
  spring-boot/src/main/java/com/tody/dayori/diary/dto/DiaryResponse.java
  spring-boot/src/main/java/com/tody/dayori/diary/error/ErrorCode.java
  spring-boot/src/main/java/com/tody/dayori/diary/repository/UserDiaryRepository.java
  spring-boot/src/main/java/com/tody/dayori/diary/service/DiaryServiceImpl.java
  spring-boot/src/main/java/com/tody/dayori/exception/RestExceptionHandler.java
  spring-boot/src/main/resources/application.yml
Labels: feature
